---
name: node-master-prod
kind: pipeline
type: docker

steps:
- name: install
  image: node:lts
  commands:
  - npm ci
  - npm audit fix --force

- name: change port
  image: alpine:3.15.4
  commands:
  - echo "It worked, master, PROMOTE!"
  - sed -i -e "s|build|Production env., build - $DRONE_BUILD_NUMBER, pearent - $DRONE_BUILD_PARENT| g" test-ci.js
  - sed -i -e "s|3000|4201|g" test-ci.js
  - cat test-ci.js

- name: scp
  image: appleboy/drone-scp
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    target: /way-tales/be-prod
    source:
      - ./*
      - !./.git/*
    rm: true

- name: restart way-tales-be-prod
  image: appleboy/drone-ssh
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    script:
      - sudo systemctl restart way-tales-be-prod

trigger:
  branch:
  - master
  event:
  - promote

---
name: node-master
kind: pipeline
type: docker

steps:
- name: install
  image: node:lts
  commands:
  - npm ci
  - npm audit fix --force

- name: change port
  image: alpine:3.15.4
  commands:
  - echo "It worked, master, test!"
  - sed -i -e "s|build|Testing env., build - $DRONE_BUILD_NUMBER|g" test-ci.js
  - sed -i -e "s|3000|4200|g" test-ci.js
  - cat test-ci.js

- name: scp
  image: appleboy/drone-scp
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    target: /way-tales/be-test
    source:
      - ./*
      - !./.git/*
    rm: true

- name: restart way-tales-be-test
  image: appleboy/drone-ssh
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    script:
      - sudo systemctl restart way-tales-be-test

trigger:
  branch:
  - master
  event:
    exclude:
    - promote

---
name: node-dev
kind: pipeline
type: docker

steps:
- name: install
  image: node:latest
  failure: ignore
  commands:
  - npm ci  
  - npm audit fix --force  

- name: npm doctor
  image: node:latest
  # failure: ignore
  commands:
  - npm doctor || exit 0

- name: change port
  image: alpine:3.15.4
  commands:
  - sed -i -e "s|build|Development env., build - $DRONE_BUILD_NUMBER|g" test-ci.js
  - sed -i -e "s|3000|4202|g" test-ci.js
  - cat test-ci.js
  - env

- name: key
  image: alpine:3.15.4
  commands:
  - echo $getbuild
  - '[ $getbuild ] && echo "It worked, Key1!" || echo "It worked, false!" '

- name: scp
  image: appleboy/drone-scp
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    target: /way-tales/be-dev
    source:
      - ./*
      - !./.git/*
    rm: true

- name: restart way-tales-be-dev
  image: appleboy/drone-ssh
  settings:
    host:
    - 192.168.56.223
    user: test
    key:
       from_secret: ssh-key
    script:
      - sudo systemctl restart way-tales-be-dev

trigger:
  branch:
  - dev
  event:
    exclude:
    - promote


---
kind: pipeline
name: notify

steps:

- name: notify
  image: drillster/drone-email
  settings:
      host:.
        from_secret: email-host
      username:.
        from_secret: email-user
      password:
        from_secret: email-passwd..
      from:.
        from_secret: email-from
      recipients: [ rb.mamchur@gmail.com, r.mamchur.we@gmail.com ]
  when:
    branch:
    - flomaster

depends_on:
- node-master
- node-dev
